# Generated by Django 4.0 on 2021-12-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_IP', models.CharField(max_length=15)),
                ('destination_IP', models.CharField(max_length=15)),
                ('info', models.TextField()),
            ],
        ),
    ]
