# Generated by Django 4.0 on 2021-12-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapacket',
            name='destination_IP',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datapacket',
            name='source_IP',
            field=models.CharField(max_length=30),
        ),
    ]
