# Generated by Django 4.0 on 2021-12-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipSearch', '0002_alter_datapacket_destination_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapacket',
            name='destination_IP',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datapacket',
            name='source_IP',
            field=models.CharField(max_length=100),
        ),
    ]
