# Generated by Django 4.0.1 on 2022-01-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[(6, 'TCP'), (17, 'UDP'), (-1, 'NONE')], default=-1, max_length=255)),
                ('length_Bytes', models.PositiveIntegerField()),
                ('schedule_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('isp', models.CharField(max_length=255)),
                ('asname', models.CharField(max_length=255)),
                ('organisation', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServerDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('domainName', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='testTable',
        ),
        migrations.AddField(
            model_name='networktraffic',
            name='destination_Address_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='home.server'),
        ),
        migrations.AddField(
            model_name='networktraffic',
            name='source_address_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='home.server'),
        ),
    ]
