# Generated by Django 4.0.1 on 2022-01-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_server_asname_remove_server_isp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
