# Generated by Django 4.0.1 on 2022-01-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_server_city_alter_server_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
