# Generated by Django 4.0.1 on 2022-01-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_server_latitude_alter_server_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networktraffic',
            name='protocol',
            field=models.CharField(max_length=255),
        ),
    ]
