# Generated by Django 4.0.1 on 2022-01-14 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_networktraffic_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServersEncounteredInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrences', models.BigIntegerField(default=0)),
                ('tcp_count', models.BigIntegerField(default=0)),
                ('udp_count', models.BigIntegerField(default=0)),
                ('total_bytes_sent', models.BigIntegerField(default=0)),
                ('ip_address_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.server')),
            ],
        ),
        migrations.DeleteModel(
            name='ServerDomains',
        ),
    ]
