# Generated by Django 4.0.1 on 2022-01-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_server_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='publicServer',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.CreateModel(
            name='DomainNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, null=True)),
                ('black_list_occur', models.PositiveIntegerField()),
                ('white_list_occur', models.PositiveIntegerField()),
                ('ip_address_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.server')),
            ],
        ),
    ]
