# Generated by Django 4.0.1 on 2022-01-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_server_publicserver_domainnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainnames',
            name='black_list_occur',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='domainnames',
            name='white_list_occur',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
