# Generated by Django 4.0.1 on 2022-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_domainnames_black_list_occur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='detectionRate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='malicousCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
