# Generated by Django 4.0.1 on 2022-03-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_server_detectionrate_server_malicouscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversencounteredinsession',
            name='iterationNumber',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
