# Generated by Django 4.0.1 on 2022-03-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_summarydifferenceboth_summarydifferencenotinboth'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarydifferencenotinboth',
            name='fileNumber',
            field=models.SmallIntegerField(null=True),
        ),
    ]
