# Generated by Django 4.0.1 on 2022-03-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_summarydifferencenotinboth_filenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarydifferenceboth',
            old_name='differenceInOccurPerServer',
            new_name='differenceInOccurenceMean',
        ),
        migrations.RenameField(
            model_name='summarydifferenceboth',
            old_name='fileOneOccurPerServer',
            new_name='fileOneOccurrences_mean',
        ),
        migrations.RenameField(
            model_name='summarydifferenceboth',
            old_name='fileTwoOccurPerServer',
            new_name='fileTwoOccurrences_mean',
        ),
        migrations.RenameField(
            model_name='summarydifferencenotinboth',
            old_name='occurrencePerServer',
            new_name='occurrences_mean',
        ),
        migrations.RemoveField(
            model_name='summarydifferenceboth',
            name='differenceInCoefficentOfStd',
        ),
        migrations.RemoveField(
            model_name='summarydifferencenotinboth',
            name='coefficentOfStd',
        ),
    ]
