# Generated by Django 4.0.1 on 2022-01-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='number',
            field=models.IntegerField(),
        ),
    ]
